#!/usr/bin/env bash

export PATH="$HOME/.apt/usr/bin:${PATH:+:$PATH}"
export LD_LIBRARY_PATH="$HOME/.apt/usr/lib/x86_64-linux-gnu:$HOME/.apt/usr/lib/i386-linux-gnu:$HOME/.apt/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export LIBRARY_PATH="$HOME/.apt/usr/lib/x86_64-linux-gnu:$HOME/.apt/usr/lib/i386-linux-gnu:$HOME/.apt/usr/lib:${LIBRARY_PATH:+:$LIBRARY_PATH}"
export INCLUDE_PATH="$HOME/.apt/usr/include:${INCLUDE_PATH:+:$INCLUDE_PATH}"
export CPATH="${INCLUDE_PATH:+:$INCLUDE_PATH}"
export CPPPATH="${INCLUDE_PATH:+:$INCLUDE_PATH}"
export PKG_CONFIG_PATH="$HOME/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:$HOME/.apt/usr/lib/i386-linux-gnu/pkgconfig:$HOME/.apt/usr/lib/pkgconfig:${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
export PYTHONPATH="$HOME/.apt/usr/lib/python2.7/dist-packages"
export SCREENDIR="$HOME/.apt/var/run/screen"

BUILD_DIR=$1
echo "Starting: LocalTunnel"
npx localtunnel --port 22023 >$BUILD_DIR/tunnelurl.txt &
tunnel_pid=$!
sleep 5
echo "Starting: The Server At Port 22023..."
screen -h 2048 -dmS server Server/Impostor.Server | tee $BUILD_DIR/server.log
main_pid=$!
sleep 2
trap "kill $tunnel_pid $main_pid" SIGTERM
trap "kill -9 $tunnel_pid $main_pid; exit" SIGKILL