#!/usr/bin/env node

"use strict";

const ngrok_authtoken = arguments[0];
const DIR = arguments[1];

const fs = require("fs"),
    ngrok = require("ngrok");

(async () => {
    const url = await ngrok.connect({
        port: 22023,
        proto: "udp",
        authtoken: ngrok_authtoken
    });
    fs.writeFile(`${DIR}/tunnel.log`, url, err => {
        if (err) throw err;
    });
})();
