#!/usr/bin/env bash

cd "$(dirname "$(readlink -f "$0")")"
npm i

echo "Starting: LocalTunnel"
./localTunnel.js &
tunnel_pid=$!
sleep 5

echo "Starting: The Server At Port 22023..."
screen -h 2048 -dmS server ./Server/Impostor.Server
main_pid=$!
sleep 2

trap "kill $tunnel_pid $main_pid" SIGTERM
trap "kill -9 $tunnel_pid $main_pid; exit" SIGKILL

echo "Starting: The Web Server"
./node_modules/http-server/bin/http-server bin/ -p $PORT
