#!/usr/bin/env bash

BIN_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
npm i --prefix $BIN_DIR -g

echo "Starting: LocalTunnel"
$BIN_DIR/localTunnel.js &
tunnel_pid=$!
sleep 5

echo "Starting: The Server At Port 22023..."
screen -h 2048 -dmS server $BIN_DIR/Server/Impostor.Server
main_pid=$!
sleep 2

trap "kill $tunnel_pid $main_pid" SIGTERM
trap "kill -9 $tunnel_pid $main_pid; exit" SIGKILL

echo "Starting: The Web Server"
$BIN_DIR/node_modules/http-server/bin/http-server bin/ -p $PORT
