#!/usr/bin/env bash

echo "Starting: LocalTunnel"
bin/localTunnel.js &
tunnel_pid=$!
sleep 5

echo "Starting: The Server At Port 22023..."
screen -h 2048 -dmS server bin/Server/Impostor.Server
main_pid=$!
sleep 2

trap "kill $tunnel_pid $main_pid" SIGTERM
trap "kill -9 $tunnel_pid $main_pid; exit" SIGKILL

echo "Starting: The Web Server"
node bin/node_modules/http-server/bin/http-server bin/ -p $PORT
