name: Check BASH Syntax
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check BASH Syntax
        run: |
          bash -n bin/compile 
          bash -n bin/detect 
          bash -n bin/release 
          bash -n opt/run
